apiVersion: batch/v1
kind: Job
metadata:
  name: create-db-tables
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: init
          image: ghcr.io/vishnu420/emp-api:1.0.0
          command: ["python", "init_db.py"]
      restartPolicy: Never

---
