# helmfile.yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

environments:
  prod:
    values:
      - envs/prod/values.yaml

releases:
  - name: emp-fullstack
    namespace: emp
    chart: ./charts/emp-fullstack
