apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
stringData:
  DB_USER: root
  DB_PASS: rootpass
  DB_NAME: empdb
  DB_HOST: myapp-mysql
