---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgC6XdezAomLDhbP8+OPsEy1doPrnPUDzXoaYtGGHVOIzbs2C92gGUVzLuq4JfP8WvNBpkS64mGh2sdToq/zmw5mzXb/R9kldlWLOKKZpwDqOW82IUAInDwCSiODt16vzKEQ+53FsLoglX6bMN8QFsFIqB+S3M+Mlq9Cm9pNesQPi77leWQ+/MNIA7z7D2JtkLcOUz3mvwfOyhx6KpzOd/H5rm+qzJ5aXP4ijVlzmvQNgw7kDGH+6f9IMZXfSBJjlCkPDoyXfPh2EClNHKiaxo6SY3bAz+Q+4qElNOI2DAwvDNVeUP1ugcsPhGXQqifL6e1z50Gy5obx2O2/KextEI1hdf4FZjhbEMfPST2P0o48Uh0QPLgldnD+py7MtEw1YaUNuIAygexQdWI/vwLlT1hT69gdn65KnRznPOWGGY7ifg6eAMc64qRH7VMhbm/kXtGQqNtibToGo0xM/tG2eUGTCHgda6JS80/KNpIbAQVKwwCpON/67VDpjabEzTN8+5duft7iw9QM20pO1CJbeIEnrkv0evkPGkCPchVQDp/If3lU+dr5W/yCZtc6mqnzZERWvbZvY716mH/WpCZyNIx4lbAWhsg8ARzROh7w+gF+vVbCnmrzEd5v7hSR93m5TAER5nQoARaPOOidrETIA6tY9YOaausIEIVJCJIA8FdkJlSmq5pSAnmpCzOPiVdf3CalJgKOw2BZ
    username: AgAWYvBs21RvNCsvUnco6SBWBLn89PaBqHdqf/g4i8wQMdB7j/0jKQ6H7Kc4UN9XygV0oLH3ttzjuRqfeRpprQSyhfL/yDFBGuTRaVclAAeb+NiUEUcbpb7zj4o3qZu9O33kHbO8VTrVERQnMX++/eIBUaBte2XDPct+LBytJp6fHGIQwj85/HO5aQnKgecZAqABA2Ixau32XNxKfULVX95RsjxkOjohwJwCpsEW+WpMbBFxw4e/wQBB20spckTHaep8uMgFAK6X+4jtocVRH4ejTHH6ONHV+eyms6o9qAMhL/FH5AWaQAQ9VVweauAp0vyCo43YVoeQrwnp1AMhaci40Yq9LUwD8NbGAp2VFXOkT5ho3+F6m9nUBvB+KltrKWQRCA38MpiOgcVwZMvC2nRGPOemepff1/28TZ8M6p7Iau3T5MyvjZLm6nzUW+lbDv5Hdix6XCayrbnBqqTb2KmMhaNzUMlX6fotLTzr6Qbc2Ivwq8mt5A7bpU3qok09JbXvNqsaqF+xZYnHYVf6rKxJsbYOONMVb3KCvSKx2xd5CScSx5mNfqWVno55bcHon/UDD9sBcOFUP6YUzE6YdLTz2MHZlxcCcUCGbW+AvStFbe3SVu2RbzFQW3p5dS4Ecfjd4WOb3InvmaolE1603IbF1LUOGn6eZeaaT/BvkSoVjXzCdFQKyjYGhSbqaQ6CJkBdPvdTxkxr
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: db-secret
      namespace: default
    type: Opaque
