
backend:
  image:
    repository: ghcr.io/vishnu420/emp-api
    tag: "1.0.0"
    pullPolicy: Always
  replicaCount: 2
  env:
    - name: DB_HOST
      value: mysql
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username

frontend:
  image:
    repository: ghcr.io/vishnu420/emp-ui
    tag: "1.0.0"
    pullPolicy: Always
  replicaCount: 1
mysql:
  auth:
    rootPassword: "use-sealed-secret"
    username: empuser
    password: "use-sealed-secret"
    database: empdb

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: emp.yourdomain.com
      paths:
        - path: /api
          serviceName: backend
          servicePort: 5000
        - path: /
          serviceName: frontend
          servicePort: 80
  tls:
    - secretName: emp-tls
      hosts:
        - emp.yourdomain.com

---