apiVersion: v2
name: emp-fullstack
version: 1.0.0

dependencies:
  - name: mysql
    version: 10.0.0
    repository: https://charts.bitnami.com/bitnami
    alias: mysql

  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"

  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
