backend:
  image:
    repository: vishnu420/emp-helm
    tag: backend
    pullPolicy: Always
  replicaCount: 1
  env:
    - name: DB_HOST
      value: mysql
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_PASSWORD
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_NAME
frontend:
  image:
    repository: vishnu420/emp-helm
    tag: frontend
    pullPolicy: Always
  replicaCount: 1

mysql:
  primary:
    persistence:
      enabled: true
      size: 1Gi

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # cert-manager.io/cluster-issuer: letsencrypt-prod  # <-- Optional: remove this if not using cert-manager
  hosts:
    - host: emp.yourdomain.com
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 5000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
  # tls:  # <-- Entire TLS block removed
  #   - secretName: emp-tls
  #     hosts:
  #       - emp.yourdomain.com

