backend:
  image:
    repository: vishnu420/emp-helm
    tag: backend
    pullPolicy: Always
  replicaCount: 1
  env:
    - name: DB_HOST
      value: mysql
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
frontend:
  image:
    repository: vishnu420/emp-helm
    tag: frontend
    pullPolicy: Always
  replicaCount: 1
  env: []
mysql:
  auth:
    rootPassword: "use-sealed-secret"
    username: empuser
    password: "use-sealed-secret"
    database: empdb

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: emp.yourdomain.com
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 5000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
  tls:
    - secretName: emp-tls
      hosts:
        - emp.yourdomain.com        
---
