apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: {{ .Values.backend.env | selectattr "name" "equalto" "DB_HOST" | first | dig "value" }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.env | selectattr "name" "equalto" "DB_USER" | first | dig "valueFrom.secretKeyRef.name" }}
                  key: {{ .Values.backend.env | selectattr "name" "equalto" "DB_USER" | first | dig "valueFrom.secretKeyRef.key" }}
